[project]
name = "Sarkaz-Translator"
version = "0.1.0"
description = "A Sarkaz-Chinese (Simplified) translator & tokenizer based on transformer, implemented on pytorch. "
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "datasets>=4.8.4",
    "hf-transfer>=0.1.9",
    "python-dotenv>=1.2.2",
    "sentencepiece>=0.2.1",
    "torch>=2.11.0",
    "tqdm>=4.67.3",
]

[[tool.uv.index]]
url = "https://mirrors.aliyun.com/pypi/simple"
default = true
